#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amplex.scms.modules.parts.classes
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="amplex")]
	public partial class partsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcat_setting(cat_setting instance);
    partial void Updatecat_setting(cat_setting instance);
    partial void Deletecat_setting(cat_setting instance);
    partial void Insertcat_size(cat_size instance);
    partial void Updatecat_size(cat_size instance);
    partial void Deletecat_size(cat_size instance);
    partial void Insertcat_part(cat_part instance);
    partial void Updatecat_part(cat_part instance);
    partial void Deletecat_part(cat_part instance);
    #endregion
		
		public partsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["amplexConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public partsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public partsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public partsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public partsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cat_setting> cat_settings
		{
			get
			{
				return this.GetTable<cat_setting>();
			}
		}
		
		public System.Data.Linq.Table<cat_size> cat_sizes
		{
			get
			{
				return this.GetTable<cat_size>();
			}
		}
		
		public System.Data.Linq.Table<cat_part> cat_parts
		{
			get
			{
				return this.GetTable<cat_part>();
			}
		}
		
		[Function(Name="dbo.cat_part_search")]
		public ISingleResult<cat_part> cat_part_search([Parameter(DbType="NVarChar(128)")] string searchText, [Parameter(DbType="Bit")] System.Nullable<bool> searchInDescription1, [Parameter(DbType="Bit")] System.Nullable<bool> searchInDescription2, [Parameter(DbType="Bit")] System.Nullable<bool> searchInDescription3, [Parameter(DbType="Bit")] System.Nullable<bool> searchInLongDescription, [Parameter(DbType="NVarChar(32)")] string orderBy, [Parameter(DbType="Bit")] System.Nullable<bool> powerSearch, [Parameter(DbType="Int")] System.Nullable<int> pageSize, [Parameter(DbType="Int")] System.Nullable<int> pageNumber, [Parameter(DbType="Int")] ref System.Nullable<int> count)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchText, searchInDescription1, searchInDescription2, searchInDescription3, searchInLongDescription, orderBy, powerSearch, pageSize, pageNumber, count);
			count = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((ISingleResult<cat_part>)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.cat_settings")]
	public partial class cat_setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _siteId;
		
		private System.Nullable<int> _searchResultsPageId;
		
		private System.Nullable<int> _searchResultsPageModuleInstanceId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteIdChanging(int value);
    partial void OnsiteIdChanged();
    partial void OnsearchResultsPageIdChanging(System.Nullable<int> value);
    partial void OnsearchResultsPageIdChanged();
    partial void OnsearchResultsPageModuleInstanceIdChanging(System.Nullable<int> value);
    partial void OnsearchResultsPageModuleInstanceIdChanged();
    #endregion
		
		public cat_setting()
		{
			OnCreated();
		}
		
		[Column(Storage="_siteId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[Column(Storage="_searchResultsPageId", DbType="Int")]
		public System.Nullable<int> searchResultsPageId
		{
			get
			{
				return this._searchResultsPageId;
			}
			set
			{
				if ((this._searchResultsPageId != value))
				{
					this.OnsearchResultsPageIdChanging(value);
					this.SendPropertyChanging();
					this._searchResultsPageId = value;
					this.SendPropertyChanged("searchResultsPageId");
					this.OnsearchResultsPageIdChanged();
				}
			}
		}
		
		[Column(Storage="_searchResultsPageModuleInstanceId", DbType="Int")]
		public System.Nullable<int> searchResultsPageModuleInstanceId
		{
			get
			{
				return this._searchResultsPageModuleInstanceId;
			}
			set
			{
				if ((this._searchResultsPageModuleInstanceId != value))
				{
					this.OnsearchResultsPageModuleInstanceIdChanging(value);
					this.SendPropertyChanging();
					this._searchResultsPageModuleInstanceId = value;
					this.SendPropertyChanged("searchResultsPageModuleInstanceId");
					this.OnsearchResultsPageModuleInstanceIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.cat_size")]
	public partial class cat_size : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private int _ordinal;
		
		private EntitySet<cat_part> _cat_parts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnordinalChanging(int value);
    partial void OnordinalChanged();
    #endregion
		
		public cat_size()
		{
			this._cat_parts = new EntitySet<cat_part>(new Action<cat_part>(this.attach_cat_parts), new Action<cat_part>(this.detach_cat_parts));
			OnCreated();
		}
		
		[Column(Storage="_id", DbType="NVarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="NVarChar(32)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_ordinal", DbType="Int NOT NULL")]
		public int ordinal
		{
			get
			{
				return this._ordinal;
			}
			set
			{
				if ((this._ordinal != value))
				{
					this.OnordinalChanging(value);
					this.SendPropertyChanging();
					this._ordinal = value;
					this.SendPropertyChanged("ordinal");
					this.OnordinalChanged();
				}
			}
		}
		
		[Association(Name="cat_size_cat_part", Storage="_cat_parts", ThisKey="id", OtherKey="sage_ProductCategoryDesc2")]
		public EntitySet<cat_part> cat_parts
		{
			get
			{
				return this._cat_parts;
			}
			set
			{
				this._cat_parts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cat_parts(cat_part entity)
		{
			this.SendPropertyChanging();
			entity.cat_size = this;
		}
		
		private void detach_cat_parts(cat_part entity)
		{
			this.SendPropertyChanging();
			entity.cat_size = null;
		}
	}
	
	[Table(Name="dbo.cat_part")]
	public partial class cat_part : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _sage_SKICPart;
		
		private System.Nullable<decimal> _sage_price;
		
		private string _sage_ID;
		
		private string _sage_Description1;
		
		private string _sage_Description2;
		
		private string _sage_Description3;
		
		private string _sage_LongDescription;
		
		private string _hash;
		
		private System.Nullable<System.DateTime> _lastUpdated;
		
		private string _imageUrl;
		
		private System.Nullable<int> _pageId;
		
		private System.Nullable<int> _instanceId;
		
		private string _sage_ProductCategoryDesc1;
		
		private string _sage_ProductCategoryDesc2;
		
		private string _sage_ProductCategoryDesc3;
		
		private string _sage_ProductCategoryDesc4;
		
		private string _sage_ProductCategoryDesc5;
		
		private EntityRef<cat_size> _cat_size;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onsage_SKICPartChanging(int value);
    partial void Onsage_SKICPartChanged();
    partial void Onsage_priceChanging(System.Nullable<decimal> value);
    partial void Onsage_priceChanged();
    partial void Onsage_IDChanging(string value);
    partial void Onsage_IDChanged();
    partial void Onsage_Description1Changing(string value);
    partial void Onsage_Description1Changed();
    partial void Onsage_Description2Changing(string value);
    partial void Onsage_Description2Changed();
    partial void Onsage_Description3Changing(string value);
    partial void Onsage_Description3Changed();
    partial void Onsage_LongDescriptionChanging(string value);
    partial void Onsage_LongDescriptionChanged();
    partial void OnhashChanging(string value);
    partial void OnhashChanged();
    partial void OnlastUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnlastUpdatedChanged();
    partial void OnimageUrlChanging(string value);
    partial void OnimageUrlChanged();
    partial void OnpageIdChanging(System.Nullable<int> value);
    partial void OnpageIdChanged();
    partial void OninstanceIdChanging(System.Nullable<int> value);
    partial void OninstanceIdChanged();
    partial void Onsage_ProductCategoryDesc1Changing(string value);
    partial void Onsage_ProductCategoryDesc1Changed();
    partial void Onsage_ProductCategoryDesc2Changing(string value);
    partial void Onsage_ProductCategoryDesc2Changed();
    partial void Onsage_ProductCategoryDesc3Changing(string value);
    partial void Onsage_ProductCategoryDesc3Changed();
    partial void Onsage_ProductCategoryDesc4Changing(string value);
    partial void Onsage_ProductCategoryDesc4Changed();
    partial void Onsage_ProductCategoryDesc5Changing(string value);
    partial void Onsage_ProductCategoryDesc5Changed();
    #endregion
		
		public cat_part()
		{
			this._cat_size = default(EntityRef<cat_size>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_sage_SKICPart", DbType="Int NOT NULL")]
		public int sage_SKICPart
		{
			get
			{
				return this._sage_SKICPart;
			}
			set
			{
				if ((this._sage_SKICPart != value))
				{
					this.Onsage_SKICPartChanging(value);
					this.SendPropertyChanging();
					this._sage_SKICPart = value;
					this.SendPropertyChanged("sage_SKICPart");
					this.Onsage_SKICPartChanged();
				}
			}
		}
		
		[Column(Storage="_sage_price", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> sage_price
		{
			get
			{
				return this._sage_price;
			}
			set
			{
				if ((this._sage_price != value))
				{
					this.Onsage_priceChanging(value);
					this.SendPropertyChanging();
					this._sage_price = value;
					this.SendPropertyChanged("sage_price");
					this.Onsage_priceChanged();
				}
			}
		}
		
		[Column(Storage="_sage_ID", DbType="VarChar(21)")]
		public string sage_ID
		{
			get
			{
				return this._sage_ID;
			}
			set
			{
				if ((this._sage_ID != value))
				{
					this.Onsage_IDChanging(value);
					this.SendPropertyChanging();
					this._sage_ID = value;
					this.SendPropertyChanged("sage_ID");
					this.Onsage_IDChanged();
				}
			}
		}
		
		[Column(Storage="_sage_Description1", DbType="VarChar(29)")]
		public string sage_Description1
		{
			get
			{
				return this._sage_Description1;
			}
			set
			{
				if ((this._sage_Description1 != value))
				{
					this.Onsage_Description1Changing(value);
					this.SendPropertyChanging();
					this._sage_Description1 = value;
					this.SendPropertyChanged("sage_Description1");
					this.Onsage_Description1Changed();
				}
			}
		}
		
		[Column(Storage="_sage_Description2", DbType="VarChar(29)")]
		public string sage_Description2
		{
			get
			{
				return this._sage_Description2;
			}
			set
			{
				if ((this._sage_Description2 != value))
				{
					this.Onsage_Description2Changing(value);
					this.SendPropertyChanging();
					this._sage_Description2 = value;
					this.SendPropertyChanged("sage_Description2");
					this.Onsage_Description2Changed();
				}
			}
		}
		
		[Column(Storage="_sage_Description3", DbType="VarChar(29)")]
		public string sage_Description3
		{
			get
			{
				return this._sage_Description3;
			}
			set
			{
				if ((this._sage_Description3 != value))
				{
					this.Onsage_Description3Changing(value);
					this.SendPropertyChanging();
					this._sage_Description3 = value;
					this.SendPropertyChanged("sage_Description3");
					this.Onsage_Description3Changed();
				}
			}
		}
		
		[Column(Storage="_sage_LongDescription", DbType="VarChar(1000)")]
		public string sage_LongDescription
		{
			get
			{
				return this._sage_LongDescription;
			}
			set
			{
				if ((this._sage_LongDescription != value))
				{
					this.Onsage_LongDescriptionChanging(value);
					this.SendPropertyChanging();
					this._sage_LongDescription = value;
					this.SendPropertyChanged("sage_LongDescription");
					this.Onsage_LongDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_hash", DbType="VarChar(256)")]
		public string hash
		{
			get
			{
				return this._hash;
			}
			set
			{
				if ((this._hash != value))
				{
					this.OnhashChanging(value);
					this.SendPropertyChanging();
					this._hash = value;
					this.SendPropertyChanged("hash");
					this.OnhashChanged();
				}
			}
		}
		
		[Column(Storage="_lastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastUpdated
		{
			get
			{
				return this._lastUpdated;
			}
			set
			{
				if ((this._lastUpdated != value))
				{
					this.OnlastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._lastUpdated = value;
					this.SendPropertyChanged("lastUpdated");
					this.OnlastUpdatedChanged();
				}
			}
		}
		
		[Column(Storage="_imageUrl", DbType="NVarChar(1024)")]
		public string imageUrl
		{
			get
			{
				return this._imageUrl;
			}
			set
			{
				if ((this._imageUrl != value))
				{
					this.OnimageUrlChanging(value);
					this.SendPropertyChanging();
					this._imageUrl = value;
					this.SendPropertyChanged("imageUrl");
					this.OnimageUrlChanged();
				}
			}
		}
		
		[Column(Storage="_pageId", DbType="Int")]
		public System.Nullable<int> pageId
		{
			get
			{
				return this._pageId;
			}
			set
			{
				if ((this._pageId != value))
				{
					this.OnpageIdChanging(value);
					this.SendPropertyChanging();
					this._pageId = value;
					this.SendPropertyChanged("pageId");
					this.OnpageIdChanged();
				}
			}
		}
		
		[Column(Storage="_instanceId", DbType="Int")]
		public System.Nullable<int> instanceId
		{
			get
			{
				return this._instanceId;
			}
			set
			{
				if ((this._instanceId != value))
				{
					this.OninstanceIdChanging(value);
					this.SendPropertyChanging();
					this._instanceId = value;
					this.SendPropertyChanged("instanceId");
					this.OninstanceIdChanged();
				}
			}
		}
		
		[Column(Storage="_sage_ProductCategoryDesc1", DbType="NVarChar(11)")]
		public string sage_ProductCategoryDesc1
		{
			get
			{
				return this._sage_ProductCategoryDesc1;
			}
			set
			{
				if ((this._sage_ProductCategoryDesc1 != value))
				{
					this.Onsage_ProductCategoryDesc1Changing(value);
					this.SendPropertyChanging();
					this._sage_ProductCategoryDesc1 = value;
					this.SendPropertyChanged("sage_ProductCategoryDesc1");
					this.Onsage_ProductCategoryDesc1Changed();
				}
			}
		}
		
		[Column(Storage="_sage_ProductCategoryDesc2", DbType="NVarChar(11)")]
		public string sage_ProductCategoryDesc2
		{
			get
			{
				return this._sage_ProductCategoryDesc2;
			}
			set
			{
				if ((this._sage_ProductCategoryDesc2 != value))
				{
					if (this._cat_size.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsage_ProductCategoryDesc2Changing(value);
					this.SendPropertyChanging();
					this._sage_ProductCategoryDesc2 = value;
					this.SendPropertyChanged("sage_ProductCategoryDesc2");
					this.Onsage_ProductCategoryDesc2Changed();
				}
			}
		}
		
		[Column(Storage="_sage_ProductCategoryDesc3", DbType="NVarChar(11)")]
		public string sage_ProductCategoryDesc3
		{
			get
			{
				return this._sage_ProductCategoryDesc3;
			}
			set
			{
				if ((this._sage_ProductCategoryDesc3 != value))
				{
					this.Onsage_ProductCategoryDesc3Changing(value);
					this.SendPropertyChanging();
					this._sage_ProductCategoryDesc3 = value;
					this.SendPropertyChanged("sage_ProductCategoryDesc3");
					this.Onsage_ProductCategoryDesc3Changed();
				}
			}
		}
		
		[Column(Storage="_sage_ProductCategoryDesc4", DbType="NVarChar(11)")]
		public string sage_ProductCategoryDesc4
		{
			get
			{
				return this._sage_ProductCategoryDesc4;
			}
			set
			{
				if ((this._sage_ProductCategoryDesc4 != value))
				{
					this.Onsage_ProductCategoryDesc4Changing(value);
					this.SendPropertyChanging();
					this._sage_ProductCategoryDesc4 = value;
					this.SendPropertyChanged("sage_ProductCategoryDesc4");
					this.Onsage_ProductCategoryDesc4Changed();
				}
			}
		}
		
		[Column(Storage="_sage_ProductCategoryDesc5", DbType="NVarChar(11)")]
		public string sage_ProductCategoryDesc5
		{
			get
			{
				return this._sage_ProductCategoryDesc5;
			}
			set
			{
				if ((this._sage_ProductCategoryDesc5 != value))
				{
					this.Onsage_ProductCategoryDesc5Changing(value);
					this.SendPropertyChanging();
					this._sage_ProductCategoryDesc5 = value;
					this.SendPropertyChanged("sage_ProductCategoryDesc5");
					this.Onsage_ProductCategoryDesc5Changed();
				}
			}
		}
		
		[Association(Name="cat_size_cat_part", Storage="_cat_size", ThisKey="sage_ProductCategoryDesc2", OtherKey="id", IsForeignKey=true)]
		public cat_size cat_size
		{
			get
			{
				return this._cat_size.Entity;
			}
			set
			{
				cat_size previousValue = this._cat_size.Entity;
				if (((previousValue != value) 
							|| (this._cat_size.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cat_size.Entity = null;
						previousValue.cat_parts.Remove(this);
					}
					this._cat_size.Entity = value;
					if ((value != null))
					{
						value.cat_parts.Add(this);
						this._sage_ProductCategoryDesc2 = value.id;
					}
					else
					{
						this._sage_ProductCategoryDesc2 = default(string);
					}
					this.SendPropertyChanged("cat_size");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
