#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scms.modules.special.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="amplex")]
	public partial class specialDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertscms_special_form_eventhandler(scms_special_form_eventhandler instance);
    partial void Updatescms_special_form_eventhandler(scms_special_form_eventhandler instance);
    partial void Deletescms_special_form_eventhandler(scms_special_form_eventhandler instance);
    #endregion
		
		public specialDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public specialDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public specialDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public specialDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<scms_special_form_eventhandler> scms_special_form_eventhandlers
		{
			get
			{
				return this.GetTable<scms_special_form_eventhandler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.scms_special_form_eventhandler")]
	public partial class scms_special_form_eventhandler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _formId;
		
		private int _eventHandlerId;
		
		private int _parentPageId;
		
		private System.Nullable<int> _templateId;
		
		private System.Nullable<int> _titleFieldId;
		
		private System.Nullable<int> _imageFieldId;
		
		private System.Nullable<int> _descriptionFieldId;
		
		private System.Nullable<int> _associatedDateFieldId;
		
		private System.Nullable<bool> _imageTranslate;
		
		private string _imageTranslationMode;
		
		private System.Nullable<int> _imageTranslationHeight;
		
		private System.Nullable<int> _imageTranslationWidth;
		
		private System.Nullable<int> _imageTranslationBackgroundColor;
		
		private System.Nullable<int> _siteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnformIdChanging(int value);
    partial void OnformIdChanged();
    partial void OneventHandlerIdChanging(int value);
    partial void OneventHandlerIdChanged();
    partial void OnparentPageIdChanging(int value);
    partial void OnparentPageIdChanged();
    partial void OntemplateIdChanging(System.Nullable<int> value);
    partial void OntemplateIdChanged();
    partial void OntitleFieldIdChanging(System.Nullable<int> value);
    partial void OntitleFieldIdChanged();
    partial void OnimageFieldIdChanging(System.Nullable<int> value);
    partial void OnimageFieldIdChanged();
    partial void OndescriptionFieldIdChanging(System.Nullable<int> value);
    partial void OndescriptionFieldIdChanged();
    partial void OnassociatedDateFieldIdChanging(System.Nullable<int> value);
    partial void OnassociatedDateFieldIdChanged();
    partial void OnimageTranslateChanging(System.Nullable<bool> value);
    partial void OnimageTranslateChanged();
    partial void OnimageTranslationModeChanging(string value);
    partial void OnimageTranslationModeChanged();
    partial void OnimageTranslationHeightChanging(System.Nullable<int> value);
    partial void OnimageTranslationHeightChanged();
    partial void OnimageTranslationWidthChanging(System.Nullable<int> value);
    partial void OnimageTranslationWidthChanged();
    partial void OnimageTranslationBackgroundColorChanging(System.Nullable<int> value);
    partial void OnimageTranslationBackgroundColorChanged();
    partial void OnsiteIdChanging(System.Nullable<int> value);
    partial void OnsiteIdChanged();
    #endregion
		
		public scms_special_form_eventhandler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formId", DbType="Int NOT NULL")]
		public int formId
		{
			get
			{
				return this._formId;
			}
			set
			{
				if ((this._formId != value))
				{
					this.OnformIdChanging(value);
					this.SendPropertyChanging();
					this._formId = value;
					this.SendPropertyChanged("formId");
					this.OnformIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventHandlerId", DbType="Int NOT NULL")]
		public int eventHandlerId
		{
			get
			{
				return this._eventHandlerId;
			}
			set
			{
				if ((this._eventHandlerId != value))
				{
					this.OneventHandlerIdChanging(value);
					this.SendPropertyChanging();
					this._eventHandlerId = value;
					this.SendPropertyChanged("eventHandlerId");
					this.OneventHandlerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentPageId", DbType="Int NOT NULL")]
		public int parentPageId
		{
			get
			{
				return this._parentPageId;
			}
			set
			{
				if ((this._parentPageId != value))
				{
					this.OnparentPageIdChanging(value);
					this.SendPropertyChanging();
					this._parentPageId = value;
					this.SendPropertyChanged("parentPageId");
					this.OnparentPageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_templateId", DbType="Int")]
		public System.Nullable<int> templateId
		{
			get
			{
				return this._templateId;
			}
			set
			{
				if ((this._templateId != value))
				{
					this.OntemplateIdChanging(value);
					this.SendPropertyChanging();
					this._templateId = value;
					this.SendPropertyChanged("templateId");
					this.OntemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titleFieldId", DbType="Int")]
		public System.Nullable<int> titleFieldId
		{
			get
			{
				return this._titleFieldId;
			}
			set
			{
				if ((this._titleFieldId != value))
				{
					this.OntitleFieldIdChanging(value);
					this.SendPropertyChanging();
					this._titleFieldId = value;
					this.SendPropertyChanged("titleFieldId");
					this.OntitleFieldIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageFieldId", DbType="Int")]
		public System.Nullable<int> imageFieldId
		{
			get
			{
				return this._imageFieldId;
			}
			set
			{
				if ((this._imageFieldId != value))
				{
					this.OnimageFieldIdChanging(value);
					this.SendPropertyChanging();
					this._imageFieldId = value;
					this.SendPropertyChanged("imageFieldId");
					this.OnimageFieldIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptionFieldId", DbType="Int")]
		public System.Nullable<int> descriptionFieldId
		{
			get
			{
				return this._descriptionFieldId;
			}
			set
			{
				if ((this._descriptionFieldId != value))
				{
					this.OndescriptionFieldIdChanging(value);
					this.SendPropertyChanging();
					this._descriptionFieldId = value;
					this.SendPropertyChanged("descriptionFieldId");
					this.OndescriptionFieldIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_associatedDateFieldId", DbType="Int")]
		public System.Nullable<int> associatedDateFieldId
		{
			get
			{
				return this._associatedDateFieldId;
			}
			set
			{
				if ((this._associatedDateFieldId != value))
				{
					this.OnassociatedDateFieldIdChanging(value);
					this.SendPropertyChanging();
					this._associatedDateFieldId = value;
					this.SendPropertyChanged("associatedDateFieldId");
					this.OnassociatedDateFieldIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageTranslate", DbType="Bit")]
		public System.Nullable<bool> imageTranslate
		{
			get
			{
				return this._imageTranslate;
			}
			set
			{
				if ((this._imageTranslate != value))
				{
					this.OnimageTranslateChanging(value);
					this.SendPropertyChanging();
					this._imageTranslate = value;
					this.SendPropertyChanged("imageTranslate");
					this.OnimageTranslateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageTranslationMode", DbType="NVarChar(32)")]
		public string imageTranslationMode
		{
			get
			{
				return this._imageTranslationMode;
			}
			set
			{
				if ((this._imageTranslationMode != value))
				{
					this.OnimageTranslationModeChanging(value);
					this.SendPropertyChanging();
					this._imageTranslationMode = value;
					this.SendPropertyChanged("imageTranslationMode");
					this.OnimageTranslationModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageTranslationHeight", DbType="Int")]
		public System.Nullable<int> imageTranslationHeight
		{
			get
			{
				return this._imageTranslationHeight;
			}
			set
			{
				if ((this._imageTranslationHeight != value))
				{
					this.OnimageTranslationHeightChanging(value);
					this.SendPropertyChanging();
					this._imageTranslationHeight = value;
					this.SendPropertyChanged("imageTranslationHeight");
					this.OnimageTranslationHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageTranslationWidth", DbType="Int")]
		public System.Nullable<int> imageTranslationWidth
		{
			get
			{
				return this._imageTranslationWidth;
			}
			set
			{
				if ((this._imageTranslationWidth != value))
				{
					this.OnimageTranslationWidthChanging(value);
					this.SendPropertyChanging();
					this._imageTranslationWidth = value;
					this.SendPropertyChanged("imageTranslationWidth");
					this.OnimageTranslationWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageTranslationBackgroundColor", DbType="Int")]
		public System.Nullable<int> imageTranslationBackgroundColor
		{
			get
			{
				return this._imageTranslationBackgroundColor;
			}
			set
			{
				if ((this._imageTranslationBackgroundColor != value))
				{
					this.OnimageTranslationBackgroundColorChanging(value);
					this.SendPropertyChanging();
					this._imageTranslationBackgroundColor = value;
					this.SendPropertyChanged("imageTranslationBackgroundColor");
					this.OnimageTranslationBackgroundColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="Int")]
		public System.Nullable<int> siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
