//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amplex.sites.amplex._masters.controls {
    
    
    public partial class mainnav {
        
        /// <summary>
        /// menuAbout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::amplex.sites.failsourcing._controls.MainNavItem menuAbout;
        
        /// <summary>
        /// menuFeatured control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::amplex.sites.failsourcing._controls.MainNavItem menuFeatured;
        
        /// <summary>
        /// menuProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::amplex.sites.failsourcing._controls.MainNavItem menuProducts;
        
        /// <summary>
        /// menuNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::amplex.sites.failsourcing._controls.MainNavItem menuNews;
        
        /// <summary>
        /// menuContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::amplex.sites.failsourcing._controls.MainNavItem menuContact;
    }
}
