//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scms.modules.submission.controls
{


    public partial class submission
    {

        /// <summary>
        /// titleHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl titleHeading;

        /// <summary>
        /// hlHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hlHeading;

        /// <summary>
        /// divTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divTitle;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSource;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSubmitter;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCredit;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSubmissionLink;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanSubmitter;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanDocumentCredit;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lableDocumentCredit;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAdmin;
        protected global::System.Web.UI.WebControls.LinkButton btnEdit;
        protected global::System.Web.UI.WebControls.CheckBox checkApproved;
        protected global::System.Web.UI.WebControls.CheckBox checkFeatured;
        protected global::System.Web.UI.WebControls.CheckBox checkDeleted;


        /// <summary>
        /// divSubTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSubTitle;

        /// <summary>
        /// divVoting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divVoting;

        /// <summary>
        /// voting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::scms.modules.submission.controls.voting voting;

        /// <summary>
        /// divPostDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPostDate;

        /// <summary>
        /// divImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divImage;

        /// <summary>
        /// image control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image image;

        /// <summary>
        /// divVideo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divVideo;

        /// <summary>
        /// divDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDescription;
    }
}
